application: openid-gae
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

inbound_services:
- warmup

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  mime_type: image/x-icon

- url: /_ah/warmup
  login: admin 
  script: wsgi.app

- url: /.*
  script: wsgi.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?.*\.cmd$
- ^(.*/)?LICENSE$
- ^(.*/)?README\.md$
- ^(.*/)?makefile$
- ^(.*/)?\.git.*$
